/// Date dimension, one row per Settlement Day
table 'Date'
	dataCategory: Time

	/// DERIVED: Expected half-hours under selected dates, including clock changes
	measure 'Expected Settlement Periods' = SUM('Date'[Expected Periods])
		formatString: #,##0
		displayFolder: Monitor
		annotation EvidenceClass = DERIVED

	/// DERIVED: Contiguous local Settlement Day calendar
	column 'Date'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: settlement_date
		annotation EvidenceClass = DERIVED
		formatString: yyyy-MM-dd

	/// DERIVED: UTC elapsed time between London midnights / 30 minutes
	column 'Expected Periods'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: expected_periods
		annotation EvidenceClass = DERIVED

	/// OBSERVED: Year
	column 'Year'
		dataType: int64
		summarizeBy: none
		sourceColumn: year
		annotation EvidenceClass = OBSERVED

	/// OBSERVED: Month Number
	column 'Month Number'
		dataType: int64
		summarizeBy: none
		sourceColumn: month
		annotation EvidenceClass = OBSERVED

	/// OBSERVED: Month
	column 'Month'
		dataType: string
		summarizeBy: none
		sourceColumn: month_name
		annotation EvidenceClass = OBSERVED
		sortByColumn: 'Month Number'

	/// OBSERVED: Weekday
	column 'Weekday'
		dataType: string
		summarizeBy: none
		sourceColumn: weekday
		annotation EvidenceClass = OBSERVED

	/// DERIVED: Clock Change
	column 'Clock Change'
		dataType: boolean
		summarizeBy: none
		sourceColumn: clock_change
		annotation EvidenceClass = DERIVED

	partition 'Date' = m
		mode: import
		source =
			let
				Run = Json.Document(File.Contents(DataFolder & "/processed/run.json")),
				Source = if Record.FieldOrDefault(Run, "status", "unknown") <> "success" then error "Latest pipeline run did not succeed. Rebuild validated outputs before refreshing." else Csv.Document(File.Contents(DataFolder & "/processed/dates.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"settlement_date", type date}, {"expected_periods", Int64.Type}, {"year", Int64.Type}, {"month", Int64.Type}, {"month_name", type text}, {"weekday", type text}, {"clock_change", type logical}}, "en-GB")
			in
				Typed
